name: Docker

on:
  push:
    tags:
      - v*

jobs:
  docker-release-candidate:
    if: contains(github.ref, '-rc')
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push

  docker-latest:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') && !contains(github.ref, '+') && !contains(github.ref, '_') }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-latest