name: Docker Nightly

on:
  schedule:
    # Run at 1:00 AM and 1:00 PM UTC every day (every 12 hours)
    - cron: "0 1,13 * * *"
  workflow_dispatch:

jobs:
  docker-nightly:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-nightly
      profile: maxperf

  docker-nightly-profiling:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-nightly-profiling
      profile: profiling