name: Reusable Docker Build
on:
  workflow_call:
    inputs:
      make-target:
        description: 'Makefile target to run'
        required: true
        type: string
      profile:
        description: 'Cargo profile to use'
        required: false
        type: string
        default: 'release'
env:
  IMAGE_NAME: ${{ github.repository_owner }}/bera-reth
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bera-reth
  DOCKER_USERNAME: ${{ github.actor }}
jobs:
  docker-build:
    runs-on: ubuntu-latest-large
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      # use cosign for keyless signing of docker images
      - name: Install cosign
        # if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.9.2
        with:
          cosign-release: 'v2.5.3'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 32
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
      - name: Build and push Docker image
        id: build-and-push
        run: |
          DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} PROFILE=${{ inputs.profile }} make ${{ inputs.make-target }}
          # Get digest from the first tag in docker-meta output
          TAG=$(echo "${{ steps.docker-meta.outputs.tags }}" | head -n1 | cut -d: -f2)
          DIGEST=$(docker buildx imagetools inspect ${{ env.DOCKER_IMAGE_NAME }}:${TAG} --format "{{json .Manifest}}" | jq -r '.digest')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT
      - name: Sign the published Docker image
        # if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.docker-meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
