name: Docker

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (builds but doesn't push)"
        type: boolean
        default: true

jobs:
  docker-release-candidate:
    if: contains(github.ref, '-rc') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push
      dry-run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true' }}

  docker-latest:
    if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') && !contains(github.ref, '+') && !contains(github.ref, '_') }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-latest